name: Rust CI

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check
  
  clippy:
    name: Clippy Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev \
            libjack-jackd2-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxcb1-dev \
            libxcb-util-dev \
            libxcb-render0-dev \
            libxcb-shape0-dev \
            libxcb-xfixes0-dev \
            libxcb-icccm4-dev \
            libxcb-dri2-0-dev \
            mesa-common-dev \
            libgl1-mesa-dev \
            libxcursor-dev \
            pkg-config
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
  
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev \
            libjack-jackd2-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxcb1-dev \
            libxcb-util-dev \
            libxcb-render0-dev \
            libxcb-shape0-dev \
            libxcb-xfixes0-dev \
            libxcb-icccm4-dev \
            libxcb-dri2-0-dev \
            mesa-common-dev \
            libgl1-mesa-dev \
            libxcursor-dev \
            pkg-config
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build library
        run: cargo build --workspace --all-targets
